-- MySQL Script generated by MySQL Workbench
-- Wed Jun 26 21:56:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza



-- -----------------------------------------------------
-- Table `pizza`.`funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`funcionarios` ;

CREATE TABLE IF NOT EXISTS `pizza`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`produtos` ;

CREATE TABLE IF NOT EXISTS `pizza`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `preco` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`clientes` ;

CREATE TABLE IF NOT EXISTS `pizza`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `pizza`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `pizza`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`produtos_has_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`produtos_has_pedidos` ;

CREATE TABLE IF NOT EXISTS `pizza`.`produtos_has_pedidos` (
  `produtos_id` INT NOT NULL,
  `pedidos_id` INT NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`produtos_id`, `pedidos_id`),
  INDEX `fk_produtos_has_pedidos_pedidos1_idx` (`pedidos_id` ASC) ,
  INDEX `fk_produtos_has_pedidos_produtos1_idx` (`produtos_id` ASC) ,
  CONSTRAINT `fk_produtos_has_pedidos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `pizza`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `pizza`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`sabores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`sabores` ;

CREATE TABLE IF NOT EXISTS `pizza`.`sabores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`tamanhos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`tamanhos` ;

CREATE TABLE IF NOT EXISTS `pizza`.`tamanhos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `pizza`.`pizzas` (
  `sabores_id` INT NOT NULL,
  `tamanhos_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedidos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sabores_has_tamanhos_tamanhos1_idx` (`tamanhos_id` ASC) ,
  INDEX `fk_sabores_has_tamanhos_sabores1_idx` (`sabores_id` ASC) ,
  INDEX `fk_pizzas_pedidos1_idx` (`pedidos_id` ASC) ,
  CONSTRAINT `fk_sabores_has_tamanhos_sabores1`
    FOREIGN KEY (`sabores_id`)
    REFERENCES `pizza`.`sabores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sabores_has_tamanhos_tamanhos1`
    FOREIGN KEY (`tamanhos_id`)
    REFERENCES `pizza`.`tamanhos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzas_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `pizza`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;